name: voicebot_german_2
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/voicebot_german_2
  original_url: https://huggingface.co/spaces/Chris4K/voicebot_german_2

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
